### ISSUE TITLE
Dependency chain in README

### ISSUE THREAD

**Issue by hfrappier** [JeffyCN/libv4l-rkmpp#1]
It would be helpful to track which `librockchip-mpp` is required and which version of `chromium-browser` is compatible

**Comment by JeffyCN** [comment]
it's hard to be done because:
1/ mpp is versioned with git commit id, and it changes(rebased) a lot. so i would prefer to use the newest version or the one with closest commit date

2/ for chromium, it is not about version but some local patches to enable V4L2 VDA/VEA, which is mentioned in the readme: "This plugin is tested with [this chromium browser]" with a link.

**Comment by hfrappier** [comment]
1) Are you always building against the `release` or `develop` branch of `librockchip_mpp`?

**Comment by JeffyCN** [comment]
> 1. Are you always building against the `release` or `develop` branch of `librockchip_mpp`

this has been used in the rockchip SDKs, which would be built in 2 ways:
1/ fixed versions of libv4l-rkmpp, mpp and kernel(yes, the kernel version might be important too) in release version of SDKs (tested when releasing)
2/ newest versions of libv4l-rkmpp, mpp and kernel in develop version of SDKs

i mostly focus on 2/
