### ISSUE TITLE
Chromium 91 support

### ISSUE THREAD

**Issue by hfrappier** [JeffyCN/libv4l-rkmpp#3]
With Chromium 91+ focusing mainly on vaapi, would it be worth it to revive rockchip-va-driver instead?

**Comment by JeffyCN** [comment]
Well,
1/ The rockchip-va-driver is no longer maintained(out-dated and not zero-copy)
2/ Chromium 91+ would still support v4l2 VDA(since there are lots of chromebook using v4l2 dec/enc)
3/ I know there are people working on a new vaapi implement for the mainline kernel's v4l2 dec/enc driver(not for rockchip though, but for the same kernel driver). I haven't test that, not sure could it work with chromium vaapi VDA. Besides we are mainly focus on our BSP kernel :(

**Comment by hfrappier** [comment]
Thanks for the quick reply!
V4L2 will indeed be supported for chromeos builds. I should have specified that VAAPI seems to be the main focus for linux.

**Comment by JeffyCN** [comment]
right, for arm linux, i think chromeos is still focus on v4l2(for exynos/tegra/mtk and rockchip). but for desktop linux chromium it's indeed vaapi.

having v4l2 vda with desktop linux requires a few hacks, and that part seems not changed much in recent chromium versions, so guessing it's fine to use it so far.

**Comment by hfrappier** [comment]
Indeed. For reference, https://github.com/RidgeRun/chromium-jetson-accelerated.git has support for 90

**Comment by JeffyCN** [comment]
huh, i'm mainly use this plugin with meta-browser's chromium(wayland/x11):
https://github.com/JeffyCN/meta-rockchip/tree/master/dynamic-layers/recipes-browser/chromium

and i'm planing to port it to chromium r91.
